name: Bug Report
description: Report a problem with the platform
title: "[BUG]: "
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Crossplane
        - ArgoCD
        - Tekton Pipeline
        - Application
        - Security (Istio/Cilium/Gatekeeper)
        - Observability (Prometheus/Grafana/Loki)
        - KEDA Autoscaling
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: What went wrong?
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Deploy X
        2. Apply Y
        3. Observe error Z
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste error messages or stack traces
      render: shell
