apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.aws.network.platform.example.com
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: network.platform.example.com/v1alpha1
    kind: XNetwork

  resources:
    # VPC
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        metadata:
          labels:
            crossplane-managed: "true"
        spec:
          forProvider:
            region: us-east-1
            cidrBlock: "10.0.0.0/16"
            enableDnsHostnames: true
            enableDnsSupport: true
            tags:
              Name: platform-vpc
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.enableDnsHostnames
          toFieldPath: spec.forProvider.enableDnsHostnames
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.enableDnsSupport
          toFieldPath: spec.forProvider.enableDnsSupport
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.vpcId

    # Internet Gateway
    - name: internet-gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-igw
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Subnet - AZ1
    - name: private-subnet-az1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: private
            az: az1
            crossplane-managed: "true"
        spec:
          forProvider:
            region: us-east-1
            availabilityZone: us-east-1a
            cidrBlock: "10.0.1.0/24"
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-private-az1
              type: private
              managed-by: crossplane
              kubernetes.io/role/internal-elb: "1"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sa"

    # Private Subnet - AZ2
    - name: private-subnet-az2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: private
            az: az2
            crossplane-managed: "true"
        spec:
          forProvider:
            region: us-east-1
            availabilityZone: us-east-1b
            cidrBlock: "10.0.2.0/24"
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-private-az2
              type: private
              managed-by: crossplane
              kubernetes.io/role/internal-elb: "1"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sb"

    # Public Subnet - AZ1
    - name: public-subnet-az1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: public
            az: az1
            crossplane-managed: "true"
        spec:
          forProvider:
            region: us-east-1
            availabilityZone: us-east-1a
            cidrBlock: "10.0.101.0/24"
            mapPublicIpOnLaunch: true
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-public-az1
              type: public
              managed-by: crossplane
              kubernetes.io/role/elb: "1"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sa"

    # Public Subnet - AZ2
    - name: public-subnet-az2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: public
            az: az2
            crossplane-managed: "true"
        spec:
          forProvider:
            region: us-east-1
            availabilityZone: us-east-1b
            cidrBlock: "10.0.102.0/24"
            mapPublicIpOnLaunch: true
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-public-az2
              type: public
              managed-by: crossplane
              kubernetes.io/role/elb: "1"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: string
              string:
                fmt: "%sb"

    # NAT Gateway EIP
    - name: nat-eip
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: EIP
        spec:
          forProvider:
            region: us-east-1
            domain: vpc
            tags:
              Name: platform-nat-eip
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # NAT Gateway
    - name: nat-gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: NATGateway
        spec:
          forProvider:
            region: us-east-1
            allocationIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
                az: az1
            tags:
              Name: platform-nat
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Route Table
    - name: public-route-table
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-public-rt
              type: public
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Route Table
    - name: private-route-table
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: platform-private-rt
              type: private
              managed-by: crossplane
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Route to Internet Gateway
    - name: public-route
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          forProvider:
            region: us-east-1
            destinationCidrBlock: "0.0.0.0/0"
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
            gatewayIdSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Route to NAT Gateway
    - name: private-route
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          forProvider:
            region: us-east-1
            destinationCidrBlock: "0.0.0.0/0"
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: private
            natGatewayIdSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Subnet Association AZ1
    - name: public-rt-assoc-az1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-east-1
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
                az: az1
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Subnet Association AZ2
    - name: public-rt-assoc-az2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-east-1
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                type: public
                az: az2
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Subnet Association AZ1
    - name: private-rt-assoc-az1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-east-1
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: private
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                type: private
                az: az1
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Subnet Association AZ2
    - name: private-rt-assoc-az2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-east-1
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                type: private
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                type: private
                az: az2
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
