apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
  namespace: chatapp
data:
  MONGODB_URI: "mongodb://admin:changeme123@mongodb:27017/chatapp?authSource=admin"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp
  namespace: chatapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: chatapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  namespace: chatapp
  labels:
    app: chatapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp
          image: node:18-alpine
          command: ["/bin/sh"]
          args:
            - -c
            - |
              # Placeholder for chatapp code
              # In Phase 2, this will use the actual chatapp Docker image
              echo "Chatapp placeholder - waiting for Phase 2"
              while true; do sleep 3600; done
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: chatapp-config
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - echo alive
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - echo ready
            initialDelaySeconds: 5
            periodSeconds: 3
