apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
# Install Gatekeeper via kustomize remote
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.14.0/deploy/gatekeeper.yaml


