apiVersion: network.platform.example.com/v1alpha1
kind: Network
metadata:
  name: platform-network
  namespace: default
spec:
  parameters:
    provider: aws
    region: us-east-1
    cidrBlock: "10.0.0.0/16"
    enableDnsHostnames: true
    enableDnsSupport: true
