# IMPORTANT: This is an EXAMPLE. Use SealedSecrets or external secret management in production.
# Generate token: openssl rand -base64 32
apiVersion: v1
kind: Secret
metadata:
  name: elasticache-auth-token
  namespace: crossplane-system
type: Opaque
stringData:
  token: "CHANGE_ME_GENERATE_SECURE_TOKEN"
  # Example generation command:
  # kubectl create secret generic elasticache-auth-token \
  #   --from-literal=token=$(openssl rand -base64 32) \
  #   -n crossplane-system
